FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8080

# For production, build the app
# RUN npm run build

# For development
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]